services:
  app:
    build:
      context: .
    ports:
      - ":5000"

  nginx: # 웹서버(리버스 프록시)
    build:
      context: .
      dockerfile: Dockerfile.nginx # NginX 설정 파일이 포함된 Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"